/*Generated by WaveMaker Studio*/

package com.hrdb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.hrdb.service.VacationService;


import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wordnik.swagger.annotations.*;

import com.hrdb.*;
import com.hrdb.service.*;


/**
 * Controller object for domain model class Vacation.
 * @see com.hrdb.Vacation
 */

@RestController(value = "Hrdb.VacationController")
@Api(value = "/hrdb/Vacation", description = "Exposes APIs to work with Vacation resource.")
@RequestMapping("/hrdb/Vacation")
public class VacationController {

    private static final Logger LOGGER = LoggerFactory.getLogger(VacationController.class);

	@Autowired
	@Qualifier("hrdb.VacationService")
	private VacationService vacationService;


	@RequestMapping(value = "/search", method = RequestMethod.POST)
	@ApiOperation(value = "Returns the list of Vacation instances matching the search criteria.")
	public Page<Vacation> findVacations( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
		LOGGER.debug("Rendering Vacations list");
		return vacationService.findAll(queryFilters, pageable);
	}

	@RequestMapping(value = "/", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the list of Vacation instances.")
	public Page<Vacation> getVacations(Pageable pageable) {
		LOGGER.debug("Rendering Vacations list");
		return vacationService.findAll(pageable);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the total count of Vacation instances.")
	public Long countAllVacations() {
		LOGGER.debug("counting Vacations");
		Long count = vacationService.countAll();
		return count;
	}


    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the Vacation instance associated with the given id.")
    public Vacation getVacation(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Vacation with id: {}" , id);
        Vacation instance = vacationService.findById(id);
        LOGGER.debug("Vacation details with id: {}" , instance);
        return instance;
    }
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the Vacation instance associated with the given id.")
    public boolean deleteVacation(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Vacation with id: {}" , id);
        Vacation deleted = vacationService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the Vacation instance associated with the given id.")
    public Vacation editVacation(@PathVariable("id") Integer id, @RequestBody Vacation instance) throws EntityNotFoundException {
        LOGGER.debug("Editing Vacation with id: {}" , instance.getId());
        instance.setId(id);
        instance = vacationService.update(instance);
        LOGGER.debug("Vacation details with id: {}" , instance);
        return instance;
    }




	@RequestMapping(value = "/", method = RequestMethod.POST)
	@ApiOperation(value = "Creates a new Vacation instance.")
	public Vacation createVacation(@RequestBody Vacation instance) {
		LOGGER.debug("Create Vacation with information: {}" , instance);
		instance = vacationService.create(instance);
		LOGGER.debug("Created Vacation with information: {}" , instance);
	    return instance;
	}

	/**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
	protected void setVacationService(VacationService service) {
		this.vacationService = service;
	}
}

